# Schema for the configuration files of the San Diego Weather module.
sand_weather.settings:
  type: config_object
  label: 'San Diego Weather settings'
  mapping:
    weather_url:
      type: uri
      label: 'Url to get weather from'
    interval:
      type: integer
      label: 'The interval at which the weather is refreshed'
