_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
protect_all_forms: false
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: false
element_name: url
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_feedback_form: true
  contact_message_personal_form: false
  node_application_form: false
  node_article_form: false
  node_blog_form: false
  node_bucket_form: false
  node_business_resource_form: false
  node_date_form: false
  node_department_form: false
  node_department_document_form: false
  node_department_parent_form: false
  node_digital_archives_photos_form: false
  node_event_form: false
  node_external_data_form: false
  node_hero_form: false
  node_location_form: false
  node_mayoral_artifacts_form: false
  node_notification_form: false
  node_outreach_form: false
  node_outreach2_form: false
  node_outreach_article2_form: false
  node_registration_form: false
  node_resources_form: false
  node_reusable_component_form: false
  node_sand_gallery_form: false
  node_sidebar_block_context_form: false
  node_slide_form: false
  node_webform_form: false
  comment_comment_form: false
