_core:
  default_config_hash: fcx2bfv-TfdQ_hGuvq4GkK3SAeANYibuVJMcEJBGG38
langcode: en
password:
  per_page_or_global: per_page_or_global
  protected_pages_session_expire_time: '30'
  protected_pages_global_password: $S$E3k.66LCT5x5PkBQ4CF7TZWsdbivCA5AnFFt2/zJDEQIMgUzypMf
email:
  subject: 'Please visit this new page'
  body: "Hello,\r\n\r\nYou have been invited to view the following password protected page.\r\n\r\nPage Url = [protected-page-url]\r\n\r\nPage Password = password here\r\n\r\nPlease contact the Web Team at webteam@sandiego.gov if you have any questions.\r\n\r\nThank you,\r\n\r\nWeb Team\r\nCity of San Diego"
others:
  protected_pages_title: 'Protected Page -- Enter password'
  protected_pages_description: 'The web page you are trying to view is protected by a password. Please enter the password below to proceed.'
  protected_pages_password_fieldset_legend: 'Password Required'
  protected_pages_password_label: 'Enter password'
  protected_pages_submit_button_text: Submit
  protected_pages_incorrect_password_msg: 'An incorrect password was submitted. Please check your password and try again.'
