_core:
  default_config_hash: gbxsfZiC2MMjzyiqbCPrKXXxlhQDa0pMNs0FSt_33ds
enable: false
address: sdgovweb@sandiego.gov
roles: {  }
allowed: ''
description: true
message: true
mailkeys: ''
mailkeys_skip: ''
