_core:
  default_config_hash: n9_PfxJ1-y-bJWzVyQ8yS7SW22sVaexdCTH43Sw3Dik
field_source_name: field_source_name
mappings:
  1:
    source: documentum
    url_field: field_document_url
    from: 'http://'
    to: 'https://'
source_field: field_source
queue: 0
webdata: null
no_text_body_status: no-text
fetch: 0
utf8threechar: 0
