_core:
  default_config_hash: x6bhN6WZwfVUI_LLMvRJIUW_2c26VTaBozbfXmJWmro
seckit_xss:
  csp:
    checkbox: true
    vendor-prefix:
      x: false
      webkit: false
    report-only: false
    default-src: "'self' about: data: blob: analytics.google.com bam.nr-data.net app.energycap.com *.kampyle.com *.nr-data.net *.force.com *.browsealoud.com *.constantcontact.com *.ctctcdn.com www.facebook.com *.google.com *.google-analytics.com *.googleapis.com *.googletagmanager.com *.gstatic.com cascade2.libchat.com px.ads.linkedin.com track.mailerlite.com *.medallia.com *.monsido.com *.newrelic.com *.sdge.com *.sharethis.com speech.speechstream.net public.tableau.com *.twimg.com *.twitter.com www.wageworks.com static.wixstatic.com cola.unh.edu www.consumer.ftc.gov sandiego.gov *.sandiego.gov stats.g.doubleclick.net bam.nr-data.net speech.speechstream.net firstsearch.oclc.org *.granicus.com *.weather.gov"
    script-src: "'self' about: data: blob: *.live-sdgov.pantheonsite.io *.twitter.com *.polyfill.io *.amazonaws.com *.hdrelay.com manage.hdrelay.com *.monsido.com *.googleapis.com 'unsafe-eval' 'unsafe-inline' *.kampyle.com *.medallia.com visualsponline.azurewebsites.net *.nr-data.net *.force.com *.newrelic.com *.google-analytics.com *.ads-twitter.com *.browsealoud.com *.cloudflare.com *.ctctcdn.com *.google.com *.googleadservices.com *.googletagmanager.com *.gstatic.com t.ifvox.com v2.libanswers.com *.licdn.com www.peakdemocracy.com *.sharethis.com public.tableau.com cdn.syndication.twimg.com *.cloudfront.net connect.facebook.net *.newrelic.com vjs.zencdn.net firstsearch.oclc.org *.typeform.com *.instagram.com cdn.rawgit.com cdn.jsdelivr.net a.fsdn.com/con/js/sftheme/vendor/modernizr.3.3.1.custom.js cdn.datatables.net"
    object-src: ''
    style-src: "'self' 'unsafe-inline' *.force.com *.browsealoud.com ws.sharethis.com events.constantcontact.com static.ctctcdn.com *.googleapis.com *.gstatic.com cdn-images.mailchimp.com static.mailerlite.com ton.twimg.com platform.twitter.com vjs.zencdn.net cdnjs.cloudflare.com cdn.jsdelivr.net cdn.datatables.net"
    img-src: "'self' data: blob: * www.google.es *.browsealoud.com *.constantcontact.com *.ctctcdn.com www.facebook.com *.google.com *.google-analytics.com *.googleapis.com *.googletagmanager.com *.gstatic.com cascade2.libchat.com px.ads.linkedin.com track.mailerlite.com *.monsido.com *.newrelic.com *.sdge.com *.sharethis.com public.tableau.com *.twimg.com *.twitter.com www.wageworks.com static.wixstatic.com *.ytimg.com cola.unh.edu www.consumer.ftc.gov sandiego.gov *.sandiego.gov stats.g.doubleclick.net bam.nr-data.net firstsearch.oclc.org www.google.it www.google.pt www.google.com.ph www.google.com.om www.google.co.uk www.google.com.mx www.google.de www.google.co.in"
    media-src: ''
    frame-src: "'self' *.waze.com td.doubleclick.net app.energycap.com api.exchqzdata.com datasd.typeform.com data: *.medallia.com *.amazonaws.com *.arcgis.com sandiego.bibliocommons.com www.facebook.com support.gale.com *.google.com portal.hdontap.com manage.hdrelay.com cdn.knightlab.com stories.opengov.com www.opentownhall.com www.peakdemocracy.com prezi.com sandiego.seamlessdocs.com public.tableau.com app.truelook.com *.twitter.com player.vimeo.com youtube.com www.youtube.com www.youtube-nocookie.com *.sandiego.gov *.sharethis.com c.sharethis.mgr.consensu.org *.granicus.com app.powerbigov.us *.instagram.com *.hylandcloud.com app.truelook.cloud *.smartsheet.com padlet.com *.indigov.com"
    frame-ancestors: ''
    child-src: ''
    font-src: "'self' data: *.force.com themes.googleusercontent.com fonts.gstatic.com *.sandiego.gov vjs.zencdn.net fonts.googleapis.com cdnjs.cloudflare.com"
    connect-src: "'self' data: blob: www.google.ca *.hdrelay.com *.kampyle.com *.nr-data.net *.force.com *.browsealoud.com *.constantcontact.com *.ctctcdn.com www.facebook.com *.google.com *.google-analytics.com *.googleapis.com *.googletagmanager.com *.gstatic.com cascade2.libchat.com px.ads.linkedin.com track.mailerlite.com *.medallia.com *.monsido.com *.newrelic.com *.sdge.com *.sharethis.com speech.speechstream.net public.tableau.com *.twimg.com *.twitter.com www.wageworks.com static.wixstatic.com cola.unh.edu www.consumer.ftc.gov sandiego.gov *.sandiego.gov stats.g.doubleclick.net bam.nr-data.net speech.speechstream.net firstsearch.oclc.org *.granicus.com *.us-west-2.amazonaws.com wss://*.us-west-2.amazonaws.com"
    report-uri: /report-csp-violation
    upgrade-req: false
    policy-uri: ''
  x_xss:
    seckit_x_xss_option_disable: Disabled
    seckit_x_xss_option_0: '0'
    seckit_x_xss_option_1: 1;
    seckit_x_xss_option_1_block: '1; mode=block'
    select: 0
seckit_csrf:
  origin: true
  origin_whitelist: ''
seckit_clickjacking:
  js_css_noscript: false
  noscript_message: 'Sorry, you need to enable JavaScript to visit this website.'
  x_frame: '1'
  x_frame_allow_from: ''
seckit_ssl:
  hsts: false
  hsts_subdomains: false
  hsts_max_age: 2592000
  hsts_preload: false
seckit_ct:
  expect_ct: false
  max_age: 86400
  report_uri: ''
  enforce: false
seckit_fp:
  feature_policy: false
  feature_policy_policy: ''
seckit_various:
  from_origin: false
  from_origin_destination: same
  referrer_policy: true
  referrer_policy_policy: no-referrer-when-downgrade
  disable_autocomplete: false
