_core:
  default_config_hash: RMy8ch2MOT68bCD63OGZQRdMk2pD6UXPEZMuCIisbfs
langcode: en
activate: true
auth_source: default-sp
login_link_display_name: 'Federated login'
login_link_show: true
user_name: NameId
unique_id: uId
mail_attr: main
header_no_cache: true
role:
  population: ''
  eval_every_time: false
register_users: true
allow:
  set_drupal_pwd: true
  default_login: true
  default_login_roles:
    administrator: administrator
    content_owner: content_owner
  default_login_users: '1,314,354,421,422'
logout_goto_url: ''
user_register_original: null
sync:
  mail: true
  user_name: true
autoenablesaml: false
debug: false
secure: false
httponly: false
