_core:
  default_config_hash: GnciVSpJGwXtuBeAb60PIb2f1e3gGcwKpoyRpxgQ3gM
show_on_admin: 0
alert_styles: "success|Green\r\nwarning|Yellow\r\nerror|Red\r\nemergency|Emergency"
display_order: ascending
refresh_interval: 15
automatic_refresh: 0
cache_max_age: 15
